staging-settings:
  rpcs:
    - chain-name: ethereum-testnet-sepolia-worldchain-1
      url: https://worldchain-sepolia.g.alchemy.com/v2/Q77PtNprVdeLU7HT5-_caVZZfHrwRWzL

production-settings:
  rpcs:
    - chain-name: ethereum-mainnet-worldchain-1
      url: https://worldchain-sepolia.g.alchemy.com/v2/Q77PtNprVdeLU7HT5-_caVZZfHrwRWzL
